export const caseData = {
  id: "2026/57",
  title: "State vs Ramesh Kumar",
  priority: "High Priority",
  caseType: "Criminal Investigation",
  act: ["Section 375 IPC", "Section 498A IPC"],
  policeStation: "Central Town Police Station",
  leadInvestigator: "Inspector Vikram Singh",
  complainant: "Mrs. Asha Sharma",
  accused: "Ramesh Kumar",
  lastUpdated: "2026-05-12",
  status: "Judgment Delivered",
  outcome: "Case Disposed",
  cctnsReference: "HR-GGN-0029/2026",
  cctnsPortal: "CCTNS Portal - NCRB (Crime and Criminal Tracking Network & System)",
  events: [
    {
      key: "dd-gd",
      category: "Case Registration",
      label: "DD / GD Entry — Case Logging",
      hindi: "जनरल डायरी प्रविष्टि",
      date: "2026-04-03",
      time: "10:30 hrs",
      description: "General Diary (GD) entry made as first step. Preliminary screening to assess if complaint involves cognizable offence. No formal investigation initiated yet.",
      legal: "Police Act §44, CrPC §154",
      completed: true,
    },
    {
      key: "fir",
      category: "Case Registration",
      label: "FIR Registration & IIF-1 (CCTNS Entry)",
      hindi: "प्रथम सूचना रिपोर्ट (FIR) एवं IIF-1",
      date: "2026-04-03",
      time: "11:00 hrs",
      description: "FIR formally registered under CrPC §154. IIF-1 (Incident Information Form-1) simultaneously entered in CCTNS Portal - NCRB for national tracking. Investigating Officer deputed. Unique case number assigned in CCTNS database.",
      legal: "CrPC §154, CCTNS Guidelines",
      reference: "FIR No. 0142/2024, IIF-1: GGN-IIF1-2024-0142",
      completed: true,
    },
    {
      key: "iif2",
      category: "Investigation",
      label: "Crime Scene Inspection (IIF-II)",
      hindi: "अपराध स्थल निरीक्षण (IIF-II)",
      date: "2026-04-05",
      description: "Crime scene visited and inspected. Panchnama prepared. Evidence photographed and videographed. IIF-II form filed in CCTNS. Physical evidence seized and catalogued.",
      legal: "CrPC §100, §165, CCTNS IIF-II entry",
      completed: true,
    },
    {
      key: "spot-visit",
      category: "Investigation",
      label: "Witness Statements & Interrogation",
      date: "2026-04-06",
      description: "Witness statements recorded under CrPC §161. Accused interrogated for facts. Case diary maintained with investigation progress.",
      legal: "CrPC §161, §162",
      completed: true,
    },
    {
      key: "arrest",
      category: "Enforcement Action",
      label: "Accused Arrested & Production",
      date: "2026-04-08",
      description: "Accused arrested and produced before JMFC within 24 hours. Rights under CrPC §50 explained. Medical examination conducted.",
      legal: "CrPC §41, §50, §57",
      completed: true,
    },
    {
      key: "seizure",
      category: "Evidence Management",
      label: "Property Seizure & Malkhana Deposit",
      date: "2026-04-09",
      description: "Seized articles deposited in Malkhana (police evidence warehouse). Each article given unique MK number. Chain of custody maintained.",
      legal: "CrPC §102, Police Rules §49",
      completed: true,
    },
    {
      key: "diary",
      category: "Documentation",
      label: "Case Diary & Investigation Progress",
      date: "2026-04-12",
      description: "Investigation diary updated with statements, evidence collection, and progress. CCTNS milestones updated for real-time tracking.",
      legal: "CrPC §172",
      completed: true,
    },
    {
      key: "chargesheet",
      category: "Court Filing",
      label: "Charge-sheet Filed (Final Report §173 CrPC)",
      date: "2026-04-20",
      description: "Charge-sheet (final investigation report) prepared and filed with court. Lists prosecution witnesses, documentary evidence, and material articles. All evidence must be attached.",
      legal: "CrPC §173",
      reference: "Chargesheet No. CS-0142/2024",
      completed: true,
    },
    {
      key: "cognizance",
      category: "Judicial Stage",
      label: "JMFC Takes Cognizance & Court Assessment",
      date: "2026-04-22",
      description: "JMFC (Judicial Magistrate First Class) reviews charge-sheet and takes cognizance under CrPC §190(1)(b). Court assesses prima facie case. Case registered for trial in court.",
      legal: "CrPC §190, §191, §225",
      completed: true,
    },
    {
      key: "commitment",
      category: "Judicial Stage",
      label: "Commitment to Sessions Court (CrPC §209)",
      date: "2026-04-25",
      description: "For offences punishable with imprisonment >7 years or serious crimes, JMFC commits case to Sessions Court under §209 CrPC. Case transferred to ASJ (Additional Sessions Judge) for trial.",
      legal: "CrPC §209, §210",
      note: "Section 375 IPC punishable with imprisonment up to 7 years - may be tried by JMFC itself. Section 498A is cognizable and can be tried by JMFC.",
      completed: true,
    },
    {
      key: "trial-start",
      category: "Trial Proceedings",
      label: "Trial Commenced - Prosecution Evidence",
      date: "2026-05-02",
      description: "Trial proceedings begin. Prosecution witnesses examined. Documentary exhibits presented. CCTNS Portal updated with trial status and hearing dates.",
      legal: "CrPC §231, §232, Evidence Act §135",
      completed: true,
    },
    {
      key: "judgment",
      category: "Disposition",
      label: "Judgment Delivered & Case Disposal",
      date: "2026-05-12",
      description: "Court delivered final judgment. Conviction/Acquittal pronounced. Sentence awarded if convicted. Case marked as disposed in CCTNS Portal - NCRB. Appeal period initiated.",
      legal: "CrPC §353, §354, §355",
      completed: true,
    },
  ],
};
